package com.kotlin.marvel.logback.exception

class NoFoundException: Exception() {
}